### ISSUE TITLE
multi level yml check

### ISSUE THREAD

**Issue by shahzeb79** [ketanTechracers/schema-validator#12]
Required not working correctly on multi level file. For example
I define schema as:
```
person: 
   name:
      type: string
      required: true
   dob:
      type: string
car:
   name:
      type: string
      required: true
```
and my yml under test can be:
```
car:
    name: 'BMW'
```
So it should not complain person.name is required. 
Currently it complain that person.name is missing. It should only complain if upper level object exist eg
```
car:
    name: 'BMW'
person:
   dob: 24-10
```
