### ISSUE TITLE
Wildcard parent

### ISSUE THREAD

**Issue by claydanford** [ketanTechracers/schema-validator#14]
Hi great module. Thanks for this one.

I have a need to check child key/values under parents with wildcards.

Example:

```YAML
foo:
  bar:
    color: blue
  baz:
    color: red
```

Where color needs to be checked but it's immediate parent is not always known: `foo.*.color`. Anyway to accomplish this?
