### ISSUE TITLE
how to validate array of elements?

### ISSUE THREAD

**Issue by glensc** [ketanTechracers/schema-validator#2]
```yml
services:
- name: a name
  ports:
    - port: 81
      service: web
    - port: 10101
      service: api

- name: another name
  ports:
    - port: 2801
      name: api
    - port: 2802
      name: mysql
    - port: 31975
      service: nodePort/public api
    - port: 31976
      service: nodePort/internal api
```

**Comment by Vonor** [comment]
I have it like this:
Schema:
```yaml
VirtualHost:
  listen:
    -
      type: number
      required: true
```
and the Yaml to validate:
```yaml
VirtualHost:
  listen:
  - 80
  - 443
```

Result: SUCCESS : Schema Validated Successfully

**Comment by ketanTechracers** [comment]
closing this issue as we got a way to check for array elements.

**Comment by TheRealAstoo** [comment]
Hello @ketanTechracers 😃 

I just tried to do the same and it's always a success even if I make it wrong : 

My schema: 
```yaml
- question:
    type: string
  goodAnswers:
    - 
      type: string
      required: true
  wrongAnswers:
    - 
      type: string
      required: true
```


My  yaml file to check: 
``yaml

`- question: Which of these proposals are **primitive** types?
  goodAnswers:
    - "`Number`"
    - "`String`"
    - "`Boolean`"
    - 42
  wrongAnswers:
    - "`Object`"
   ```
