### ISSUE TITLE
Validate Regex?

### ISSUE THREAD

**Issue by Vonor** [ketanTechracers/schema-validator#3]
Hi,

I want to validate whether the given yaml parameter matches a certain regex. Is this possible somehow?

Example:

```yaml
IP:
  type: string
  required: true
  regex: ^\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b$
```
